# -*- coding: utf-8 -*-
"""python_kiran_TheEnchantedForest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mYmeBfx9ZNNLuTVsjs1vjtcEruosFc02
"""

def find_path(n):
    if n % 2 == 0 or n < 3 or n > 15:
        raise ValueError("Input must be an odd integer between 3 and 15.")
    magic_square = [[0] * n for _ in range(n)]
    i, j = 0, n // 2
    for num in range(1, n**2 + 1):
        magic_square[i][j] = num
        i -= 1
        j += 1
        if i < 0:
            i = n - 1
        if j == n:
            j = 0
        if magic_square[i][j] != 0:
            i += 2
            j -= 1
            if i >= n:
                i -= n
            if j < 0:
                j = n - 1
    return magic_square
n = int(input("Enter the size of list which is odd and lies between 3 and 15 "))
magic_square = find_path(n)
for row in magic_square:
    print(row)