# -*- coding: utf-8 -*-
"""python_kiran_magicmirror.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wwctk7ccajoepM_vYonvV3hVQFTJhT5T
"""

input_string=input("Enter the magic word:")
split_list=list(input_string)
rev_list = split_list[::-1]
pal_string=""
for i in range(len(split_list)):
  if(split_list[i] == rev_list[i]):
    pal_string+=split_list[i]
small_pal=""
if (pal_string==""):
  print("Error")
else:
  if(len(pal_string)%2==0):
    small_pal=pal_string[int(len(pal_string)/2-1)]+pal_string[int(len(pal_string)/2)]
    print(small_pal)
  else:
    small_pal=pal_string[int(len(pal_string)/2-1):int(len(pal_string)/2+2)]
    print(small_pal)



