# -*- coding: utf-8 -*-
"""python_kiran_CallCipher.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YGq3vUVAw3cD-t6eOiJyvJFXqszq8_SW
"""

def text_to_num(phone_number):
    translation_table = str.maketrans("ABCDEFGHIJKLMNOPQRSTUVWXYZ", "22233344455566677778889999")

    numerical_form = phone_number.upper().translate(translation_table)

    return numerical_form

phone_number=input("Enter the phone number:")
text_to_num(phone_number)