# -*- coding: utf-8 -*-
"""python_kiran_ CamelsonaString.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mYmeBfx9ZNNLuTVsjs1vjtcEruosFc02
"""

import re

def split_string_by_capital_word(s):
    result = re.findall(r'[A-Z]?[a-z]+', s)
    return result
s = input("Enter a String:")
result = split_string_by_capital_word(s)
print("Number of words:", len(result))