# -*- coding: utf-8 -*-
"""python_kiran_peakyblinders.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K6d-JU_TJqaFHicJTDhlkA5IYCtGUHxM
"""

import numpy as np

string_list=input("Enter the amount stolen by the theives:")
money_list=string_list.split()
for i in range(len(money_list)):
  money_list[i]=int(money_list[i])
average_money=np.mean(money_list)
count=0
for i in range(len(money_list)):
  if(money_list[i]>=average_money):
    count+=money_list[i]
print("Money greater than and equal to average:",count)

