# -*- coding: utf-8 -*-
"""python_kiran_ TheHeist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BsofeH2TD6fsWw1GSaYJ38RLUo_ZWsuQ
"""

import numpy as np

flag = 0

def gold_find(box, target):
    global flag
    np.sort(box)
    start = 0
    end = len(box) - 1

    while start <= end:
        middle = (start + end) // 2
        midpoint = box[middle]
        if midpoint > target:
            end = middle - 1
        elif midpoint < target:
            start = middle + 1
        else:
            flag = 1
            return midpoint

string1_list = input("Enter the elements in box1 separated by spaces:")
box1 = string1_list.split()
string2_list = input("Enter the elements in box2 separated by spaces:")
box2 = string2_list.split()
string3_list = input("Enter the elements in box3 separated by spaces:")
box3 = string3_list.split()

target = "gold"
gold_find(box1, target)
if flag == 1:
    print("Element found in box1 ")
else:
    gold_find(box2, target)
    if flag == 1:
        print("Element found in box2 ")
    else:
        gold_find(box3, target)
        if flag == 1:
            print("Element found in box3 ")
        else:
            print("No element found")

