# -*- coding: utf-8 -*-
"""python_kiran_sunburnt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K6d-JU_TJqaFHicJTDhlkA5IYCtGUHxM
"""

string_list=input("Enter the height of the trees separated by spaces:")
height_list=string_list.split()
for i in range(len(height_list)):
  height_list[i]=int(height_list[i])
max_height=height_list[0]
count=1
for i in range(len(height_list)):
  if(max_height < height_list[i]):
    count+=1
    max_height=height_list[i]
print("The no. of buildings that can see sunsine:",count)