# -*- coding: utf-8 -*-
"""python_kiran_CoderofConversions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18aJnLUNMEvEA-OFOEEC8t_4xJPoJZdPF
"""

def binaryconvertor(sum):
  if(sum>=1):
    binaryconvertor(sum//2)
    print(sum%2,end="")
a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
sum=a+b
binaryconvertor(sum)